### ISSUE TITLE
"com.ifedorenko.m2e.mavendev" for m2e 1.5 not available

### ISSUE THREAD

**Issue by mtamme** [ifedorenko/com.ifedorenko.m2e.mavendev#4]
Hi,

I cannot find "com.ifedorenko.m2e.mavendev" for m2e 1.5 anymore and m2e 1.6 is not out AFAIK. Can you provide the m2e 1.5 compatible version on Eclipse Marketplace?

Thanks,
Martin

**Comment by ifedorenko** [comment]
I guess this issue resolved itself last month, when m2e 1.6 was released.
