### ISSUE TITLE
usage data collection as optional part

### ISSUE THREAD

**Issue by martinlippert** [ifedorenko/com.ifedorenko.m2e.mavendev#6]
It would be great if the usage data collection feature of takari would be an optional part here (not included in the main feature here). The marketplace entry could still include it (maybe marked as optional as well), but it would be awesome if I could use the dev feature on its own.

The background: I would like to include this in a development version of the spring tool suite, but I can't include the usage data collection (for various reasons). For now I will go ahead, fork the project, setup my own CI build for it, my own internal update site, etc. But it would be much easier if the usage data collection piece would not be included in the feature definition.

**Comment by paulvi** [comment]
:+1:

**Comment by ifedorenko** [comment]
Few observations/comments

You don't need to fork this codebase to remove usage stats collection, just define your feature that includes bundles that you need.

You probably still have to fork this codebase to sign the bundles and features. I can't justify the cost of signing certificate for what is essentially my personal dev tool, but I assume commercial Eclipse distributions like STS or JBossTools need everything signed.

Regardless if you choose to define new feature or fork, please make sure it is clear that all support questions go to STS, not here. I'd appreciate if you included some sort of attribution in feature name or description, however.

I recommend you maintain internal update site and CI build for this code. I can't guarantee timely builds or reliable update site at this point. I try my best but my the time I can afford is very limited.

Development of this codebase is not, and never have been, part of any commercial operation. I am collecting usages stats so I can justify personal time I spend maintaining this code. The more users I know this code has, the more likely I choose to work on it. If you can suggest another way to estimate the user base, by sharing usage stats I assume STS collects for example, we can probably find a better way to support STS packaging requirements.

(This is early monday morning, blood caffeine level is very low, so apologies if I sound tense. Not my intend. I am glad STS finds this code useful and wants to include it).

**Comment by martinlippert** [comment]
Thanks for the additional thoughts and comments, much appreciated. I went ahead and created a fork for this, changing the feature definition to exclude the data collection, and added signing and a few other minor tweaks to get it run and upload on our build infrastructure.

I understand and agree that having this signing in place is too much to ask for a private project, perfectly understand.

I left the feature names and everything the same as before. Would that work for you as attribution? Or would you like to see something else? I am open to suggestions and happy to give you credit for this in the open. Just let me know what works for you beyond leaving the feature names/descriptions the same as in your repo.

Thanks for working on this and for sharing this under EPL!!! Much appreciated!!!

**Comment by ifedorenko** [comment]
I am not sure what's the best approach here, but I think it should be possible to tell the forked feature from the original. I wonder if it makes sense to change forked feature id and provider to yourself (or STS/Pivotal) and add something like "based on work ..." to the description? Does not matter much in the grand scheme of things, you don't have to change anything if you think I am not making sense (disclaimer: it's Friday early morning here :-) ).

**Comment by martinlippert** [comment]
Would like to give you full credit on those features, putting anything from STS/Pivotal on them doesn't seem right to me. So lets keep it as we have for the moment and gather some experience. I am aware that you can't provide any support for this in your spare time, but I expect people to hit the STS issuetracker first anyway... :-)

Thanks again!!!

**Comment by paulvi** [comment]
Gentlemen, I am honored to be here.

I would add string to feature name to be seen in About -> Details and/or other places

" by Igor Fedorenko, no support from the author"

@ifedorenko Some projects on GitHub like https://github.com/eclipse-color-theme/eclipse-color-theme and many others do consider themselves responsible to respond to raised issues and pull requests. Just state your position in README, so people know, that there is no support, only collaboration. 

By the way, if Eclipse or Pivotal could provide usage data collection service https://github.com/spring-projects/eclipse-integration-commons/issues/8
then maybe Igor could switch to that and get usage data from within STS installation as well.
But yes, that raise more questions.

**Comment by ifedorenko** [comment]
I do consider myself responsible to answer to raised issues, otherwise we wouldn't have this discussion ;-) I am undecided about pull requests, but there haven't been any I was interested to accept, so I still have time to decide.

... and good luck getting Eclipse decide anything regarding usage stats, you can start https://bugs.eclipse.org/bugs/show_bug.cgi?id=413169 and http://wiki.eclipse.org/Policies/Uploading_and_Downloading_from_Eclipse_Software_Policy

**Comment by martinlippert** [comment]
@paulvi The usage data collection from our eclipse-integration-commons project is abandoned and no longer used for your projects (Spring IDE, STS, etc.). We don't collect usage data anymore.

**Comment by ifedorenko** [comment]
Takari usages collection backend has been shutdown for quite some time now, and corresponding code was removed from maven devtools with https://github.com/ifedorenko/com.ifedorenko.m2e.mavendev/commit/c36928b2954d8950c8f36fe85b70b1e780e0ac9b.
